Increment1-3
ncyellow/devops pull request #3
Opened 2022-05-24 21:44 UTC by ncyellow

Задание первого спринта

2022-05-27 09:19 UTC, ASPecherkin requested changes
есть небольшие замечения и комментарии - если есть вопросы по ним - можем обсудить

2022-05-27 09:19 UTC, ASPecherkin commented on cmd/server/main.go
> +	"github.com/ncyellow/devops/internal/server/handlers"
просто на будущее - https://golangci-lint.run

лучше его поставить и настроить goimports , чтобы пакеты всегда были в одном порядке 

вида - сначала std , дальше внутренние пакеты и дальше внешние зависимости

2022-05-27 09:19 UTC, ASPecherkin commented on internal/agent/agent.go
> +	var data = map[string]float64{
так как метрики могут добавляться или убираться - я бы вынес создание этой map в отдельную функцию, в которую будет передан collector.metrics и на выходе уже map

2022-05-27 09:19 UTC, ASPecherkin commented on internal/server/handlers/handlers.go
> +func ValueHandler(repo storage.Repository) http.HandlerFunc {
такой способ возможен, если аргументов немного 

Ещё один вариант - 
```go
type Handler struct {
 repo storage.Repository 
 log Logger 
...
}
```

и у него уже сделать метод, который вернёт http.HandlerFunc 

Это не замечение, скорее альтернативный подход

2022-05-27 09:19 UTC, ASPecherkin commented on internal/server/storage/memory.go
> +	s.counters[name] = s.counters[name] + value
тут есть добавление значение и вопрос - может быть ли оно конкуретным? 

если да - то может произойти паника при конкуретной записи 

но судя по коду выше - вызывается оно только в одном месте и здесь всё пройдёт. 

Информация для будущего 
Если я что-то упустил - поправь меня

2022-05-27 09:38 UTC, ncyellow commented on cmd/server/main.go
> +	"github.com/ncyellow/devops/internal/server/handlers"
ok сделаю

2022-05-27 09:39 UTC, ncyellow commented on internal/agent/agent.go
> +	var data = map[string]float64{
Без проблем

2022-05-27 09:41 UTC, ncyellow commented on internal/server/storage/memory.go
> +	s.counters[name] = s.counters[name] + value
тут я не очень понял. Сейчас это дергается только из хендлера по обновлению. Ты имеешь ввиду что надо ставить Mutex? Я просто подумал раз этой темы в спринте не было то пока и делать не надо

2022-05-27 09:42 UTC, ncyellow commented on internal/server/handlers/handlers.go
> +func ValueHandler(repo storage.Repository) http.HandlerFunc {
Да я читал что есть второй вариант. Если аргументов станет много, то конечно надо будет поменять

2022-05-27 09:49 UTC, ncyellow commented
> есть небольшие замечения и комментарии - если есть вопросы по ним - можем обсудить

Замечания понятны.
Я правильно понимаю мне чтобы пройти ревью надо добавить линтер + вынос в отдельную функцию. остальное просто для информации и описание альтернативных вариантов

2022-05-28 11:54 UTC, ncyellow commented on internal/server/storage/memory.go
> +	s.counters[name] = s.counters[name] + value
сделал защиту через RWMutex

2022-05-30 19:09 UTC, ASPecherkin commented
> > есть небольшие замечения и комментарии - если есть вопросы по ним - можем обсудить
> 
> Замечания понятны. Я правильно понимаю мне чтобы пройти ревью надо добавить линтер + вынос в отдельную функцию. остальное просто для информации и описание альтернативных вариантов

да, всё верно

2022-05-30 19:10 UTC, ASPecherkin approved these changes
Всё хорошо, работу принимаю

2022-05-31 06:58 UTC, merged