Increment4-8
ncyellow/devops pull request #4
Opened 2022-06-14 21:50 UTC by ncyellow

2022-06-18 21:05 UTC, ASPecherkin commented on internal/agent/agent.go
> +		// Если пользоваться value, то все значения будут ссылаться на одну и ту же переменную - последнюю
да, всё верно - хорошо, что отметил такую особенность - на неё многие натывкаются и не понимают почему это так 👍

2022-06-18 21:11 UTC, ASPecherkin requested changes
критичных замечаний нет, большинство просто мелкие стилистические замечания

хорошая работа

2022-06-18 21:11 UTC, ASPecherkin commented on internal/server/server.go
> +	Conf config.Config
тут скорее стилистический коммент - обычно конфиг это ссылка на один объект на всё приложение 

почему так делают - если будет добавляться перечитывание конфигов в работающием приложении - ничего менять не придётся

2022-06-18 21:11 UTC, ASPecherkin commented on internal/server/storage/memory.go
> +	if metric.MType == Gauge {
я бы тут использовал switch - потому что типы метрик могут добавляться и с ним удобнее работать и читать

2022-06-18 21:11 UTC, ASPecherkin commented on internal/server/storage/memory.go
> +	if mType == Gauge {
здесь тоже можно switch сделать

2022-06-19 05:59 UTC, ncyellow commented on internal/server/server.go
> +	Conf config.Config
Заменил на указатель на конфиг и в агенте и в сервере

2022-06-19 06:01 UTC, ncyellow commented on internal/server/storage/memory.go
> +	if metric.MType == Gauge {
ok

2022-06-19 06:05 UTC, ncyellow commented on internal/agent/agent.go
> +		// Если пользоваться value, то все значения будут ссылаться на одну и ту же переменную - последнюю
на самом деле наткнулся и я. но визуально было сразу понятно что дело в этом

2022-06-20 19:37 UTC, ASPecherkin approved these changes

2022-06-20 21:26 UTC, merged